# In-Class Programming Activity, Day 5

##Nadia Berriel

## Task 1 

```{r}
library(mosaicData)
nbins = 10
```

## Task 2

```{r}
min(Galton$height)
max(Galton$height)

evenly_spaced = seq(56,79, 2.0909)
```

## Task 3
```{r}
bin_counts = table(Galton$height)
print(bin_counts)
```

## Task 4
```{r}
xL = evenly_spaced[1:length(evenly_spaced)-1]
xR = evenly_spaced[-1]
count = as.numeric(bin_counts)
hist_basics = data.frame(xL, xR, count)   #Don't undestand why this doesn't work
```

## Task 5
```{r}
make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(
              x = c(xLeft,  xLeft,  xRight, xRight, NA),
              y = c(    0, height,  height,      0, NA)
  )
  res
}
# ================
one_to_five <- function(hist_data) {
  bars <- NULL
  for (k in 1:nrow(hist_data)) {
    new_bar <- make_one_bar(hist_data[k, ])
    bars <- rbind(bars, new_bar)
  }
  bars
}
```

## Task 6
```{r}
plot(My_bars, type="n")
lines(My_bars)
polygon(My_bars)
```

## Test statements

```{r}
scoreActivity::score253(5)
```