# In-Class Programming Activity, Day 8

### Nadia Berriel

## Task 1
```{r}
x <- runif(100, min = 20, max = 70 )
y <- 5 + 3*x + 2*rnorm(100)
My_data <- data.frame(x,y)
plot(My_data$x,My_data$y)

LL_line <- function(params){
  m <- params[1]
  b <- params[2]
  sigma <- params[3]
  sum(log(dnorm(y - (m*x + b), sd = sigma))) #log-likelihood
}

testA <- LL_line(c(3,5,2))
testB <- LL_line(c(4,1,10))

starting_params <- c(4,1,10)
best <- optim(starting_params, LL_line, control = list(fnscale = -1))

```

## Task 2
```{r}
load(url("http://tiny.cc/dcf/Taxi_trips.rda"))
#waiting_time <- rexp(length(waiting_fare))

taxi_likelihood <- function(inputs){
  base_fare <- inputs[1]
  per_mile <- inputs[2]
  params <- inputs[3]
  according_to_assumptions <- (base_fare + per_mile*Taxi_trips$trip_distance)
  sum(log(dexp(Taxi_trips$fare_amount - according_to_assumptions, rate = 1 / params) + .00001))
}

testA <- c(2,2.8,3)
testB <- c(1,9,6)
taxi_likelihood(testA)
taxi_likelihood(testB)
```

```{r}
starting_params <- c(1,9,6)
best <- optim(starting_params, taxi_likelihood, control = list(fnscale = -1))
best

plot(Taxi_trips$trip_distance, Taxi_trips$fare_amount, type = "p")
abline(best$par[2], best$par[1], col = "red")
```

Components of fare due to waiting time
```{r}
waiting_fare <- (Taxi_trips$fare_amount - (best$par[2] + Taxi_trips$trip_distance*best$par[1]))/Taxi_trips$fare_amount
plot(Taxi_trips$fare_amount, waiting_fare)
```
## Test statements

```{r}
scoreActivity::score253(8)
```